---
# roles/pxe/tasks/binaries.yml
- name: Stage iPXE binaries
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ pxe.tftp_root }}/{{ item.dest }}"
    remote_src: true
    owner: root
    group: root
    mode: '0644'
  loop:
    - src: "{{ pxe.uefi_src }}"
      dest: "{{ pxe.uefi_name }}"
  when: not ansible_check_mode
