---
# roles/pxe/tasks/httpd.yml
- name: Install webserver for PXE
  package:
    name: httpd
    state: present

- name: Deploy PXE Apache config
  template:
    src: apache_pxe.conf.j2
    dest: /etc/httpd/conf.d/pxe.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart httpd
