---
- name: Controller
  block:
    - name: Include controller virtualenv tasks
      ansible.builtin.import_tasks: venv.yml
      tags:
        - venv
        - controller
    - name: Include controller hostname tasks
      ansible.builtin.import_tasks: hostname.yml
      tags:
        - hostname
        - controller
    - name: Include controller static IP tasks
      ansible.builtin.import_tasks: static_ip.yml
      tags:
        - static_ip
        - controller
    - name: Include controller IP validation tasks
      ansible.builtin.import_tasks: validate_ip.yml
      tags:
        - validate
        - controller
