---
- name: Controller
  block:
    - import_tasks: venv.yml
      tags:
        - venv
        - controller
    - import_tasks: hostname.yml
      tags:
        - hostname
        - controller
    - import_tasks: static_ip.yml
      tags:
        - static_ip
        - controller
    - import_tasks: validate_ip.yml
      tags:
        - validate
        - controller
