---
- name: Confirm controller IP matches network_config.server_ip
  ansible.builtin.assert:
    that:
      - network_config.server_ip in ansible_all_ipv4_addresses
    fail_msg: "Controller IP mismatch."
