---
# config/repos.yml
repos:
  rocky9_dvd:
    name: Rocky-9.6-x86_64-dvd.iso
    url: https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.6-x86_64-dvd.iso
    mount_path: /var/www/html/os
    vendor: rocky
    description: Rocky Linux 9 dvd for internal repo.
