---
roles:
  controller:
    stack:
      - controller_common
      - controller
      - repo_mirror
      - pxe
      - scheduler

  compute:
    stack:
      - common
      - repo_client
      - install_slurm
