---
controller_common_groups:
  - name: cluster
    system: true

controller_common_packages:
  - vim
  - git
  - curl
  - net-tools
  - python3
  - python3-devel
  - python3-pip
  - rsync
  - tmux
  - policycoreutils-python-utils
  - python3-netaddr

controller_common_users:
  - name: ansible
    groups: [wheel]
    shell: /bin/bash
    authorized_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub', errors='ignore') }}"

controller_common_sysctl:
  vm.swappiness: 10
  net.ipv4.ip_forward: 1

controller_common_limits:
  - domain: "*"
    type: "soft"
    item: "nofile"
    value: 65535
  - domain: "*"
    type: "hard"
    item: "nofile"
    value: 65535

controller_common_server_ip: "{{ network_config.server_ip }}"
controller_common_core_repo_default_distribution: rocky
controller_common_core_repo_map:
  rocky:
    - baseos
    - appstream
  almalinux:
    - baseos
    - appstream
  redhat:
    - rhel-9-for-x86_64-baseos-rpms
    - rhel-9-for-x86_64-appstream-rpms
  "red hat enterprise linux":
    - rhel-9-for-x86_64-baseos-rpms
    - rhel-9-for-x86_64-appstream-rpms
  redhatenterpriseserver:
    - rhel-9-for-x86_64-baseos-rpms
    - rhel-9-for-x86_64-appstream-rpms
  rhel:
    - rhel-9-for-x86_64-baseos-rpms
    - rhel-9-for-x86_64-appstream-rpms
controller_common_core_repo_ids: []
