---
validation_pavilion:
  enabled: true

  # Where Pavilion2 source will be installed (git clone).
  install_dir: /opt/pavilion2

  # Config dir that Pavilion will use. Weâ€™ll copy your repo configs here.
  config_dir: /opt/pavilion2/config

  # Working dir for Pavilion runs (results, logs).
  work_dir: /opt/pavilion2/work

  # Pavilion git repo (LANL public).
  repo_url: "https://github.com/lanl/Pavilion2.git"
  repo_version: "main"
  bootstrap_packages:
    - pip==24.0
    - setuptools==69.0.3
    - wheel==0.42.0
  venv_path: "{{ validation_pavilion.install_dir }}/venv"
  venv_python: "{{ validation_pavilion.install_dir }}/venv/bin/python"
  venv_pip: "{{ validation_pavilion.install_dir }}/venv/bin/pip"

  # Which Pavilion suite (file prefix) to execute by default.
  default_suite: "controller_smoke"
