---
# playbooks/controller.yml
- name: Configure controller node
  hosts: controller
  become: yes
  roles:
    - role: controller_common
    - role: controller
    - role: repo_mirror
    - role: pxe
    - role: scheduler
